apiVersion: beta/v1
kind: Package

metadata:
  name: loan-funding-package
  version: 1.0.0
  description: "LoanFunding package for MicroLoan"

spec:
  package:
    name: LoanFunding

  deployer:
    wallet:
      type: "privateKey" # Options: privateKey, mnemonic, keystore
      value: "${PRIVATE_KEY}" # Environment variable reference

