apiVersion: beta/v1
kind: PackageSystem

metadata:
  name: microloan-application
  version: 1.0.0

spec:
  system:
    name: MicroLoanPackageSystem
    constructorArgs:
      - $dependencies.packageController.address
      - $dependencies.packageViewer.address
      - ${ADMIN_ADDRESS}

  packages:
    - name: LoanRegistry

    - name: LoanFunding
      functions: "*"

    - name: LoanRepayment
      functions:
        - repayNextInstallment(uint256)

    - name: LoanTokenManager
      functions:
        - balanceOf(address,address)
        - deposit
        - withdraw

  dependencies:
    packageViewer:
      name: PackageViewer
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
    packageController:
      name: PackageController
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"

  #       Deploying contract with args: []
  # Waiting for transaction confirmation...
  # Contract deployed at: 0x5FbDB2315678afecb367f032d93F642f64180aa3
  #   ✓ PackageViewer deployed at 0x5FbDB2315678afecb367f032d93F642f64180aa3
  # Deploying contract with args: []
  # Waiting for transaction confirmation...
  # Contract deployed at: 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
  #   ✓ PackageController deployed at 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512

  deployer:
    wallet:
      type: privateKey
      value: "${PRIVATE_KEY}"
